<?php

namespace Proxies\__CG__\MS\MsBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class User extends \MS\MsBundle\Entity\User implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'MS\\MsBundle\\Entity\\User' . "\0" . 'id', '' . "\0" . 'MS\\MsBundle\\Entity\\User' . "\0" . 'user_type', '' . "\0" . 'MS\\MsBundle\\Entity\\User' . "\0" . 'nick_name', '' . "\0" . 'MS\\MsBundle\\Entity\\User' . "\0" . 'first_name', '' . "\0" . 'MS\\MsBundle\\Entity\\User' . "\0" . 'last_name', '' . "\0" . 'MS\\MsBundle\\Entity\\User' . "\0" . 'email', '' . "\0" . 'MS\\MsBundle\\Entity\\User' . "\0" . 'password', '' . "\0" . 'MS\\MsBundle\\Entity\\User' . "\0" . 'salt', '' . "\0" . 'MS\\MsBundle\\Entity\\User' . "\0" . 'status', '' . "\0" . 'MS\\MsBundle\\Entity\\User' . "\0" . 'id_chat_status', '' . "\0" . 'MS\\MsBundle\\Entity\\User' . "\0" . 'sex', '' . "\0" . 'MS\\MsBundle\\Entity\\User' . "\0" . 'descriptionMe', '' . "\0" . 'MS\\MsBundle\\Entity\\User' . "\0" . 'country', '' . "\0" . 'MS\\MsBundle\\Entity\\User' . "\0" . 'city', '' . "\0" . 'MS\\MsBundle\\Entity\\User' . "\0" . 'date_of_birth', '' . "\0" . 'MS\\MsBundle\\Entity\\User' . "\0" . 'date_reg', '' . "\0" . 'MS\\MsBundle\\Entity\\User' . "\0" . 'date_last_login', '' . "\0" . 'MS\\MsBundle\\Entity\\User' . "\0" . 'type', '' . "\0" . 'MS\\MsBundle\\Entity\\User' . "\0" . 'facebook_url', '' . "\0" . 'MS\\MsBundle\\Entity\\User' . "\0" . 'twitter_url', '' . "\0" . 'MS\\MsBundle\\Entity\\User' . "\0" . 'youtube_url', '' . "\0" . 'MS\\MsBundle\\Entity\\User' . "\0" . 'myspace_url', '' . "\0" . 'MS\\MsBundle\\Entity\\User' . "\0" . 'id_paypal', '' . "\0" . 'MS\\MsBundle\\Entity\\User' . "\0" . 'id_media', '' . "\0" . 'MS\\MsBundle\\Entity\\User' . "\0" . 'record_label', '' . "\0" . 'MS\\MsBundle\\Entity\\User' . "\0" . 'id_music_genre');
        }

        return array('__isInitialized__', '' . "\0" . 'MS\\MsBundle\\Entity\\User' . "\0" . 'id', '' . "\0" . 'MS\\MsBundle\\Entity\\User' . "\0" . 'user_type', '' . "\0" . 'MS\\MsBundle\\Entity\\User' . "\0" . 'nick_name', '' . "\0" . 'MS\\MsBundle\\Entity\\User' . "\0" . 'first_name', '' . "\0" . 'MS\\MsBundle\\Entity\\User' . "\0" . 'last_name', '' . "\0" . 'MS\\MsBundle\\Entity\\User' . "\0" . 'email', '' . "\0" . 'MS\\MsBundle\\Entity\\User' . "\0" . 'password', '' . "\0" . 'MS\\MsBundle\\Entity\\User' . "\0" . 'salt', '' . "\0" . 'MS\\MsBundle\\Entity\\User' . "\0" . 'status', '' . "\0" . 'MS\\MsBundle\\Entity\\User' . "\0" . 'id_chat_status', '' . "\0" . 'MS\\MsBundle\\Entity\\User' . "\0" . 'sex', '' . "\0" . 'MS\\MsBundle\\Entity\\User' . "\0" . 'descriptionMe', '' . "\0" . 'MS\\MsBundle\\Entity\\User' . "\0" . 'country', '' . "\0" . 'MS\\MsBundle\\Entity\\User' . "\0" . 'city', '' . "\0" . 'MS\\MsBundle\\Entity\\User' . "\0" . 'date_of_birth', '' . "\0" . 'MS\\MsBundle\\Entity\\User' . "\0" . 'date_reg', '' . "\0" . 'MS\\MsBundle\\Entity\\User' . "\0" . 'date_last_login', '' . "\0" . 'MS\\MsBundle\\Entity\\User' . "\0" . 'type', '' . "\0" . 'MS\\MsBundle\\Entity\\User' . "\0" . 'facebook_url', '' . "\0" . 'MS\\MsBundle\\Entity\\User' . "\0" . 'twitter_url', '' . "\0" . 'MS\\MsBundle\\Entity\\User' . "\0" . 'youtube_url', '' . "\0" . 'MS\\MsBundle\\Entity\\User' . "\0" . 'myspace_url', '' . "\0" . 'MS\\MsBundle\\Entity\\User' . "\0" . 'id_paypal', '' . "\0" . 'MS\\MsBundle\\Entity\\User' . "\0" . 'id_media', '' . "\0" . 'MS\\MsBundle\\Entity\\User' . "\0" . 'record_label', '' . "\0" . 'MS\\MsBundle\\Entity\\User' . "\0" . 'id_music_genre');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (User $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setUserType($userType)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUserType', array($userType));

        return parent::setUserType($userType);
    }

    /**
     * {@inheritDoc}
     */
    public function getUserType()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUserType', array());

        return parent::getUserType();
    }

    /**
     * {@inheritDoc}
     */
    public function setNickName($nickName)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNickName', array($nickName));

        return parent::setNickName($nickName);
    }

    /**
     * {@inheritDoc}
     */
    public function getNickName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNickName', array());

        return parent::getNickName();
    }

    /**
     * {@inheritDoc}
     */
    public function setFirstName($firstName)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFirstName', array($firstName));

        return parent::setFirstName($firstName);
    }

    /**
     * {@inheritDoc}
     */
    public function getFirstName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFirstName', array());

        return parent::getFirstName();
    }

    /**
     * {@inheritDoc}
     */
    public function setLastName($lastName)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLastName', array($lastName));

        return parent::setLastName($lastName);
    }

    /**
     * {@inheritDoc}
     */
    public function getLastName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLastName', array());

        return parent::getLastName();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmail($email)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmail', array($email));

        return parent::setEmail($email);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmail', array());

        return parent::getEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function setPassword($password)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPassword', array($password));

        return parent::setPassword($password);
    }

    /**
     * {@inheritDoc}
     */
    public function getPassword()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPassword', array());

        return parent::getPassword();
    }

    /**
     * {@inheritDoc}
     */
    public function setSalt($salt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSalt', array($salt));

        return parent::setSalt($salt);
    }

    /**
     * {@inheritDoc}
     */
    public function getSalt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSalt', array());

        return parent::getSalt();
    }

    /**
     * {@inheritDoc}
     */
    public function setStatus($status)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStatus', array($status));

        return parent::setStatus($status);
    }

    /**
     * {@inheritDoc}
     */
    public function getStatus()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStatus', array());

        return parent::getStatus();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdChatStatus($idChatStatus)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdChatStatus', array($idChatStatus));

        return parent::setIdChatStatus($idChatStatus);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdChatStatus()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdChatStatus', array());

        return parent::getIdChatStatus();
    }

    /**
     * {@inheritDoc}
     */
    public function setSex($sex)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSex', array($sex));

        return parent::setSex($sex);
    }

    /**
     * {@inheritDoc}
     */
    public function getSex()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSex', array());

        return parent::getSex();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescriptionMe($descriptionMe)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescriptionMe', array($descriptionMe));

        return parent::setDescriptionMe($descriptionMe);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescriptionMe()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescriptionMe', array());

        return parent::getDescriptionMe();
    }

    /**
     * {@inheritDoc}
     */
    public function setCountry($country)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCountry', array($country));

        return parent::setCountry($country);
    }

    /**
     * {@inheritDoc}
     */
    public function getCountry()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCountry', array());

        return parent::getCountry();
    }

    /**
     * {@inheritDoc}
     */
    public function setCity($city)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCity', array($city));

        return parent::setCity($city);
    }

    /**
     * {@inheritDoc}
     */
    public function getCity()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCity', array());

        return parent::getCity();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateOfBirth($dateOfBirth)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateOfBirth', array($dateOfBirth));

        return parent::setDateOfBirth($dateOfBirth);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateOfBirth()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateOfBirth', array());

        return parent::getDateOfBirth();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateReg($dateReg)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateReg', array($dateReg));

        return parent::setDateReg($dateReg);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateReg()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateReg', array());

        return parent::getDateReg();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateLastLogin($dateLastLogin)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateLastLogin', array($dateLastLogin));

        return parent::setDateLastLogin($dateLastLogin);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateLastLogin()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateLastLogin', array());

        return parent::getDateLastLogin();
    }

    /**
     * {@inheritDoc}
     */
    public function setType($type)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setType', array($type));

        return parent::setType($type);
    }

    /**
     * {@inheritDoc}
     */
    public function getType()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getType', array());

        return parent::getType();
    }

    /**
     * {@inheritDoc}
     */
    public function setFacebookUrl($facebookUrl)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFacebookUrl', array($facebookUrl));

        return parent::setFacebookUrl($facebookUrl);
    }

    /**
     * {@inheritDoc}
     */
    public function getFacebookUrl()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFacebookUrl', array());

        return parent::getFacebookUrl();
    }

    /**
     * {@inheritDoc}
     */
    public function setTwitterUrl($twitterUrl)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTwitterUrl', array($twitterUrl));

        return parent::setTwitterUrl($twitterUrl);
    }

    /**
     * {@inheritDoc}
     */
    public function getTwitterUrl()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTwitterUrl', array());

        return parent::getTwitterUrl();
    }

    /**
     * {@inheritDoc}
     */
    public function setYoutubeUrl($youtubeUrl)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setYoutubeUrl', array($youtubeUrl));

        return parent::setYoutubeUrl($youtubeUrl);
    }

    /**
     * {@inheritDoc}
     */
    public function getYoutubeUrl()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getYoutubeUrl', array());

        return parent::getYoutubeUrl();
    }

    /**
     * {@inheritDoc}
     */
    public function setMyspaceUrl($myspaceUrl)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMyspaceUrl', array($myspaceUrl));

        return parent::setMyspaceUrl($myspaceUrl);
    }

    /**
     * {@inheritDoc}
     */
    public function getMyspaceUrl()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMyspaceUrl', array());

        return parent::getMyspaceUrl();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdPaypal($idPaypal)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdPaypal', array($idPaypal));

        return parent::setIdPaypal($idPaypal);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdPaypal()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdPaypal', array());

        return parent::getIdPaypal();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdMedia($idMedia)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdMedia', array($idMedia));

        return parent::setIdMedia($idMedia);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdMedia()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdMedia', array());

        return parent::getIdMedia();
    }

    /**
     * {@inheritDoc}
     */
    public function setRecordLabel($recordLabel)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRecordLabel', array($recordLabel));

        return parent::setRecordLabel($recordLabel);
    }

    /**
     * {@inheritDoc}
     */
    public function getRecordLabel()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRecordLabel', array());

        return parent::getRecordLabel();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdMusicGenre($idMusicGenre)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdMusicGenre', array($idMusicGenre));

        return parent::setIdMusicGenre($idMusicGenre);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdMusicGenre()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdMusicGenre', array());

        return parent::getIdMusicGenre();
    }

}
